### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by jenslofgren** [paketo-buildpacks/bellsoft-liberica#135]
When trying to start a Spring Boot application in Kubernetes built with spring-boot-maven-plugin/build-image the JVM crashes with:
SIGSEGV (0xb) at pc=0x00007fd188ef62f7, pid=1, tid=0x00007fd18a05e700

Everything works as expected when using:
docker.io/paketobuildpacks/builder:0.1.174-base
Which seems to be using paketo-buildpacks/bellsoft-liberica:8.60

But any builder that uses newer versions than bellsoft-liberica:8.60 crashes with the following error message:

[log_mes.txt](https://github.com/paketo-buildpacks/bellsoft-liberica/files/7273106/log_mes.txt)

**Comment by dmikusa-pivotal** [comment]
You appear to be hitting: https://github.com/paketo-buildpacks/bellsoft-liberica/issues/131. This is a known issue.

We have a patch to disable Java NMT when using Java 8 that was released on Friday. If you are using Bellsoft Liberica 8.7.1, you'll have this patch. Java 5.17.0 has Bellsoft Liberica 8.7.1 so it has this patch by proxy.

We are working with Bellsoft Liberica to have a fix in Java 8 for this issue. We're hoping to have that included in the next quarterly updates, which should be later this month.
