### ISSUE TITLE
cpu cgroup limit is not respected for ActiveProcessorCount

### ISSUE THREAD

**Issue by cmdjulian** [paketo-buildpacks/bellsoft-liberica#205]
## What happened?
I noticed, when I set limits for CPU usage and memory, the memory limits are propagated to the jvm via launch flags. However the
cpu cores are not propagated. It is always the value of the whole available cpu cores used. For instance we're running a server with 20 cores and I gave my spring boot app 2000m cpu as a limit, which according to Kubernetes is equivalent to two dedicated logical cores. When running the application I see as one of the first lines: `Setting Active Processor Count to 20`.  
The interesting part is now, the JVM and my Spring app now take a very long time to start. Something like 23s+. When overriding the active core count via `JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2` my startup time decreases quite dramatically down to 5s.
I tried it with different values for ActiveProcessorCount and limits. It always improved start time by a considerable amount. Even with just a single core, it went down from 53s+ to 33s.  
I'm using `k3s+v1.21.8` 

Am I missing something here?

* What did you expect to happen?
   I would expect the buildpack to respect cgroup cpu limits and set the ActiveProcessorCount accordingly. 

* What was the actual behavior? Please provide log output, if possible.
   see above.

## Build Configuration
default config, no changes to settings.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
  pack v0.23.0+git-7828226

* What buildpacks are you using? Please include versions.
  paketo-buildpacks/java:
  paketo-buildpacks/ca-certificates       3.0.2
  paketo-buildpacks/bellsoft-liberica     9.0.3
  paketo-buildpacks/syft                  1.6.0
  paketo-buildpacks/gradle                6.1.0
  paketo-buildpacks/executable-jar        6.0.2
  paketo-buildpacks/apache-tomcat         7.0.4
  paketo-buildpacks/dist-zip              5.0.2
  paketo-buildpacks/spring-boot           5.3.1

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
latest paketobuildpacks/builder:tiny

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
>I would expect the buildpack to respect cgroup cpu limits and set the ActiveProcessorCount accordingly.

The active processor count helper is written in Go and uses `runtime.NumCPU()` to detect the number of CPUs.

>>NumCPU returns the number of logical CPUs usable by the current process.

My observation is that when running the ActiveProcessorCount helper with shares-based CPU limitations, it reports the full number of CPUs on the system. This is technically correct as the Linux kernel isn't going to lock you to a certain subset of CPUs, it's limiting the time your process has to run on those CPUs. You still technically have access to all of them.

My understanding is that this is what `docker run --cpus=1` and [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/) do by default.

If you instead use CPU affinity to tie your process to a specific CPU or subset of CPUs then things work as expected. This command will report the number of CPUs to which you've tied your process.

My understanding is that this is what `docker run --cpuset-cpus=1` does. I believe [Kubernetes can too](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) but again, my understanding is that it's not the default behavior.

I am not a Kubernetes expert though, so if my understanding is not correct, please do let me know.

I'm going to close out this issue as there is another similar issue open already. Please subscribe to https://github.com/paketo-buildpacks/libjvm/issues/136 to track it.

**Comment by cmdjulian** [comment]
Thanks for your answer. I think you're right.
