### ISSUE TITLE
GraalVM 22.3.0 with Java 19

### ISSUE THREAD

**Issue by HookWoods** [paketo-buildpacks/bellsoft-liberica#345]
Hello, I hope ur good!
I was trying to get spring boot native working with the java-native-image buildpacks.

The actual problem is that the repo is missing the native-image-svm for java 19 like java 17 has:
[Java 17 native](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/buildpack.toml#LL241)

Is the support soon planning? Thanks you!

Here some more info on the problems:
`Paketo Buildpack for BellSoft Liberica 9.10.0
    [creator]       unable to find dependency
    [creator]       no valid dependencies for native-image-svm, 19.0.1, and io.paketo.stacks.tiny in [(jdk, 8.0.352, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jre, 8.0.352, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jdk, 11.0.17, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jre, 11.0.17, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (native-image-svm, 11.0.17, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jdk, 17.0.5, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jre, 17.0.5, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (native-image-svm, 17.0.5, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jdk, 19.0.1, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *]) (jre, 19.0.1, [io.buildpacks.stacks.bionic io.paketo.stacks.tiny *])]
    [creator]     ERROR: failed to build: exit status 1`

**Comment by dmikusa** [comment]
This is an upstream limitation, [Bellsoft](https://bell-sw.com/pages/downloads/native-image-kit/#/nik-22-17) doesn't have NIK available for Java 19 at the moment. If/when they make it available, we'll add it. For the time being, you'd need to stick with Java 11 or 17 for building native image apps.

**Comment by MetaiR** [comment]
I have the same issue.
the jdk 19 is really important due to the new features such as project loom (which able us to use virtual threads), so please consider adding support for it

**Comment by dmikusa** [comment]
Again, we cannot add this until it's released by Bellsoft. They don't have Java 19 support yet, so we cannot add it. As soon as they do, we'll add it. We should be able to add this for [GraalVM Buildpack](https://github.com/paketo-buildpacks/graalvm) though. Give us a few days to get that updated and released, you can then use [these instructions](https://paketo.io/docs/howto/java/#use-an-alternative-java-native-image-toolkit) to use GraalVM instead of Bellsoft NIK.

**Comment by dmikusa** [comment]
A couple of notes here:

1. According to our vendor Bellsoft, they are not going to support Java 19 in NIK. It goes out of support in Jan 2023, so it's not really enough time. They are contemplating support for Java 20, and will definitely support Java 21 which is the next LTS. Their general strategy is to support the LTS versions, but they may support some non-LTS versions as well.
2. GraalVM has experimental support for Java 19, so I added this into the GraalVM buildpack. You can use that if you want to try out Java 19.

To build with GraalVM, see [these instructions](https://paketo.io/docs/howto/java/#use-an-alternative-java-native-image-toolkit).

It's basically like this though:

```
pb my-cool-app -b paketo-buildpacks/graalvm -b urn:cnb:builder:paketo-buildpacks/java -e BP_NATIVE_IMAGE=true -e BP_JVM_VERSION=19
```

Or set the buildpack list in build.gradle or pom.xml if you're using the Spring Boot Gradle/Maven build tools.

**Comment by MetaiR** [comment]
@dmikusa 
thanks for all of ur effort in this matter.
could u please represent a simple pom.xml or build.gradle in gist or somewhere else? it would be very very helpful

**Comment by dmikusa** [comment]
See the [maven docs](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.customization), the `<buildpacks>` tag is what you want. It takes a list of buildpacks. You would use the same two buildpacks I mentioned in my previous note. Example [here](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image.examples.buildpacks).
