### ISSUE TITLE
Does remote debug support for bellsoft NIK?

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/bellsoft-liberica#405]
When using JDK, we can set `BPL_DEBUG_PORT` and `BPL_DEBUG_ENABLED` to enable remote debugging by JVM.

When deploying Java native image, does Bellsoft NIK support remote debugging?
From [GraalVM debug](https://www.graalvm.org/latest/reference-manual/native-image/debugging-and-diagnostics/DebugInfo/#supported-features) doc， I think it's not support to enable remote debug by configuring debug port right?

And I think using `-g` to enable gdb debug is not suitable for us

Or do you know if there is any way to enable remote debugging, I can configure the remote debugging port and use IDE to attach the port when deploying Java native image.

**Comment by dmikusa** [comment]
> When using JDK, we can set BPL_DEBUG_PORT and BPL_DEBUG_ENABLED to enable remote debugging by JVM.

No, this is only supported by a JVM at the moment.

> Or do you know if there is any way to enable remote debugging, I can configure the remote debugging port and use IDE to attach the port when deploying Java native image.

I don't know of a way to make this happen, but if someone knows how to do that please open a new issue and link to docs/steps and we can add support for it.
