### ISSUE TITLE
The CI updater for Java 11 NIK is failing

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/bellsoft-liberica#424]
## Expected Behavior

It should run successfully.

## Steps to Reproduce

Looks like https://github.com/paketo-buildpacks/bellsoft-liberica/actions/workflows/pb-update-native-image-11.yml has been failing for a couple of weeks.

## Motivations

Fix updates.

**Comment by pivotal-david-osullivan** [comment]
Closed in #441
