### ISSUE TITLE
How to replace the JRE download address or put bellsoft-jre15.0.1+9-linux-amd64.tar.gz into the image that I have downloaded.

### ISSUE THREAD

**Issue by raigors** [paketo-buildpacks/bellsoft-liberica#69]
## What happened?
`
[INFO] [creator] BellSoft Liberica JRE 15.0.1: Contributing to layer

[INFO] [creator] Downloading from https://github.com/bell-sw/Liberica/releases/download/15.0.1+9/bellsoft-jre15.0.1+9-linux-amd64.tar.gz

[INFO] [creator] unable to invoke layer creator

[INFO] [creator] unable to get dependency jre

[INFO] [creator] unable to download https://github.com/bell-sw/Liberica/releases/download/15.0.1+9/bellsoft-jre15.0.1+9-linux-amd64.tar.gz
`
Please provide some details about the task you are trying to accomplish and
what went wrong.

* What were you attempting to do?

I want to build springboot application as image with the following command:
`mvn spring-boot:build-image`

* What did you expect to happen?
Downloading bellsoft-jre15.0.1+9-linux-amd64.tar.gz is slow and often time out in my country.
How to replace the JRE download address or put bellsoft-jre15.0.1+9-linux-amd64.tar.gz into the image that I have downloaded.
Thanks.

**Comment by uqix** [comment]
@shaopro FYI:

https://paketo.io/docs/buildpacks/configuration/#dependency-mappings

https://github.com/spring-projects/spring-boot/issues/23518
