### ISSUE TITLE
[Enhancement request] possibility to release JDK 23

### ISSUE THREAD

**Issue by patpatpat123** [paketo-buildpacks/bellsoft-liberica#724]
Hello team,

First of all, wanted to say thanks for the work you have done for JDK 23.
While the change has been merged, it seems it is pending on the release.

The last release so far, [10.8.4](https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v10.8.4), seems to have been end of September, but just before the official release of JDK 23.

Looking at the release cadence https://github.com/paketo-buildpacks/bellsoft-liberica/releases it seems you guys are doing release once every end of month (speculation here).

If that is the case, the next release which will contain JDK 23 will happen end of October.
By then, JDK 23 would have been available for a month already, while the build pack would be a month late for JDK 23 related work.

May I ask if it would be possible for you to release a version of this build pack with JDK 23?
Thank you

**Comment by patbaumgartner** [comment]
As I can see, #720 is already providing the feature. Only the release is missing.

Currently, no other Buildpacks have been upgraded to Java 23 yet. This would be the first one.

TIA

**Comment by patpatpat123** [comment]
You are correct @patbaumgartner ,

And this is what I am trying to point out. JDK 23 has been released now.
Many organizations remigrating to it.

However, there is still no support from build pack side.
It would be great is build pack team help and relrase a JDK 23 version (and hopefully, not a full month after).

Thank you!

**Comment by patbaumgartner** [comment]
hi @anthonydahanne, can you maybe help out with this'

**Comment by dmikusa** [comment]
Sorry for the delay. This has been released, https://github.com/paketo-buildpacks/java/releases/tag/v16.1.0

**Comment by dmikusa** [comment]
Please keep in mind that Paketo is an OSS project that's run by folks who generously contribute time and talent. As such there are no guarantees on when something will happen or when something will be released. 

If you have a need for faster resolution, you can either help by contributing time and talent, or you can pay for a support contract, in which case, you are then entitled to complain heartily to the company you are paying if they don't act fast enough.

If you would like to help out with buildpack maintenance, feel free to reach out on Slack or our [Discussion page](https://github.com/orgs/paketo-buildpacks/discussions/categories/java-team). We still have a need to upgrade some of our Java vendor buildpacks from 22 -> 23. This is a great way to get started & learn about buildpacks.

**Comment by patbaumgartner** [comment]
Thanks, @dmikusa for your effort! - I understand the OSS situation and I contributed already to paketo buildpacks :) It's high likely that you will find more PRs from my side coming.
