### ISSUE TITLE
Build failing when pinning JVM version to older version via BP_JVM_VERSION

### ISSUE THREAD

**Issue by schnatterer** [paketo-buildpacks/bellsoft-liberica#8]
I'd like to get deterministic builds. That why I used the `BP_JVM_VERSION` env var to pin the JVM version to `11.0.7`.
This worked well at first but suddenly the builds breaks: `no valid dependencies for jdk` (complete output at the end).

I presume this has to do with the most recent version being 11.0.8 now.
Removing the env var solves the problem but also results in non-deterministic builds.

I can see that the JRE/JDK are downloaded from [here](https://github.com/bell-sw/Liberica/releases), where 11.0.7 is still available.
It's also worth mentioning that the [spring boot docs](https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/maven-plugin/reference/html/#build-image-example-builder-configuration) explicitly mention this use case of setting a non-wildcard version.

So I think this must be a bug. Hopefully this is the correct repo to report.

Complete log output:

```
[INFO]  > Running creator
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     5 of 15 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 2.10.0
[INFO]     [creator]     paketo-buildpacks/executable-jar    2.0.1
[INFO]     [creator]     paketo-buildpacks/apache-tomcat     1.3.3
[INFO]     [creator]     paketo-buildpacks/dist-zip          1.3.7
[INFO]     [creator]     paketo-buildpacks/spring-boot       2.1.0
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Previous image with name "REMOVED" not found
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]     
[INFO]     [creator]     Paketo BellSoft Liberica Buildpack 2.10.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_VERSION              11.0.7          the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0               the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes  the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250             the number of threads in memory calculation
[INFO]     [creator]       No valid JRE available, providing matching JDK instead. Using a JDK at runtime has security implications.
[INFO]     [creator]     
[INFO]     [creator]     Paketo BellSoft Liberica Buildpack 2.10.0
[INFO]     [creator]       unable to find dependency
[INFO]     [creator]       no valid dependencies for jdk, 11.0.7, and io.buildpacks.stacks.bionic in [(jre, 8.0.262, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jre, 11.0.8, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jre, 14.0.2, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jdk, 8.0.262, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jdk, 11.0.8, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jdk, 14.0.2, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jvmkill, 1.16.0, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (memory-calculator, 4.1.0, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3])]
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

**Comment by nebhale** [comment]
Part of the issue is that you're trying to get a deterministic build by fixing a version of Java, but not a version of the buildpack itself.  If you'd pinned your builder image, rather than using the mutating tag (e.g. `gcr.io/paketo-buildpacks/builder:base` vs. `gcr.io/paketo-buildpacks/builder:0.0.389-base`), you wouldn't have experience this because the version of the Java buildpack would not change.  In fact, I think you're much better served to pin the version of the buildpack and _not_ the version of Java as the former is a strong guarantee that the images won't change (we add and change functionality in the buildpack after all).

I'll encourage the Boot team to change their documentation, to better match the [buildpack's documentation](https://github.com/paketo-buildpacks/bellsoft-liberica#configuration) 😉.

**Comment by schnatterer** [comment]
I actually read both documents, the spring boot one and the BP one. But I didn't grasp that `BP_JVM_VERSION` *must* be a wildcard. 

I saw on the logs of the build that the JDK is downloaded from [here](https://github.com/bell-sw/Liberica/releases), so I thought older versions should work as well.

Anyways, I'll try to create PRs for the docs once I'm back from holidays.

Thanks for pointing out the builder image solution, I'll give it a try!

Sorry for keeping you busy with questions and issues @nebhale   🙈

**Comment by nebhale** [comment]
@schnatterer Happy to help.  It's pretty subtle.
